kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /Users/kentaro.sudate/go/src/github.com/tmrekk121/k8s-prac/html
